var INGREDIENTS_SPREADSHEET_ID = "1VZgyE8irKxj4JUVSgT6C286jD0hxqnRAFDhNeMXqcOs";
var SHOPPING_LIST_SPREADSHEET_ID = "1Sik9slDPPFIDmRwjxegJ34fT8NW6hN6ODmwiiEiF0GU";

var INGREDIENT_TITLE = "Ingredient";
var QUANTITY_TITLE = "Quantity";
var UNITS_TITLE = "Units";

var INGREDIENT_COL_OUTPUT = "B";
var QUANTITY_COL_OUTPUT = "C";
var UNITS_COL_OUTPUT = "D";